### ISSUE TITLE
Add -config paramter

### ISSUE THREAD

**Issue by jan666** [fixje/deflux#1]
It would be nice if I could specify the config file via `-config` parameter. 

Would make it much easier to run it as cronjob (`/home/deflux/go/bin/deflux -1 -config /home/deflux/deflux.yml`) 

...or start it as daemon via `daemon -fr /home/deflux/go/bin/deflux -config /home/deflux/deflux.yml` (on FreeBSD)

without writing to /etc/.

**Comment by fixje** [comment]
fixed in 94da49c9015cf355e1e461082797d5947f0a4e2f

```
Usage of ./deflux:
  -1    write sensor state from REST API once and exit
  -config string
        specify the location of the config file (default: ./deflux.yml or /etc/deflux.yml)
  -config-gen
        generate a default config and print it on stdout
  -loglevel string
        debug | error | warning | info (default "warning")
```
